server:
    port: 8082

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/microservice
        username: postgre
        password: postgre
        driver-class-name: com.postgresql.cj.jdbc.Driver
    
    jpa:
        hibernate: 
            ddl-auto: update
        show-sql: true
